paritytech/Nomidot

CHANGELOG.md, front/gatsby/CHANGELOG.md, front/gatsby/package.json, front/gatsby/src/pages/index.tsx, lerna.json
@yjkimjunior Could you merge and try `yarn lerna:publish`, I don't think lerna:version is necessary here (but i might be wrong)
=> fix: Make lerna publish work

.eslintignore, .eslintrc.js, back/node_watcher/src/index.ts, back/node_watcher/src/nodeWatcher.ts, back/node_watcher/src/nomidot.spec.ts, back/node_watcher/src/tasks/createBlockNumber.ts, back/node_watcher/tsconfig.json, front/gatsby/tsconfig.json, front/ui-components/tsconfig.json, jest.config.js, package.json, tsconfig.json, yarn.lock
This fixes `yarn test` and `yarn lint`
(feel free not to merge if that breaks your base PR)
=> Fix linting and test

back/node_watcher/package.json, back/server/package.json, front/context/package.json, front/ui-components/package.json, front/ui-components/src/stateful/Balance.tsx, tsconfig.json
the `path` was actually causing the issue rather than solving it.
=> fix: make tsc emit properly

front/ui-components/src/BalanceDisplay.tsx, front/ui-components/src/Fab.tsx, front/ui-components/src/stateful/AddressSummary/AddressSummary.tsx, front/ui-components/src/stateful/Balance.tsx, front/ui-components/stories/Address.stories.tsx, front/ui-components/stories/AddressSummary.stories.tsx, front/ui-components/stories/BalanceDisplay.stories.tsx, front/ui-components/stories/customDecorators/index.ts, front/ui-components/stories/customDecorators/withApi.tsx
=> feat: Storybook inject api

front/context/src/KeyringContext.tsx, front/context/src/index.ts, front/ui-components/package.json, front/ui-components/src/Fab.tsx, front/ui-components/src/stateful/InputAddress.tsx, front/ui-components/stories/InputAddress.stories.tsx, front/ui-components/stories/customDecorators/withApi.tsx, front/ui-components/stories/customDecorators/withKeyring.tsx, yarn.lock
=> fix: Input Address bug

back/node_watcher/kubernetes/staging/deployments/nomidotwatcher-deployment.yaml, back/node_watcher/package.json
also chore: updating the nodewatcher service ip
=> fix: build and run the transpiled index.js for prod

front/gatsby/src/ContextGate.tsx, front/ui-components/stories/customDecorators/withApi.tsx
=> chore: Make CI green again, part2

back/node_watcher/datamodel.prisma, back/node_watcher/src/generated/prisma-client/index.ts, back/node_watcher/src/generated/prisma-client/prisma-schema.ts
I need this to be able to stitch this DB with Hasura.
Unfortunately, I couldn't find good doc for that on Prisma side, I got this from github issues ([like this one](https://github.com/prisma/prisma/issues/4412)) and it works well. Not sure what the `allocationSize` really does though :(
Note that there's a bug ([logged here](https://github.com/prisma/prisma/issues/4555)) and if you want to test it, the deployment might go well, but the node watcher will complain that it can't write. I had to `docker-compose down -v` and re `up` + deploy to have prisma not complain.
=> Set proposal id as Int

package.json, yarn.lock
=> Bump polkadot api

back/node_watcher/kubernetes/staging/deployments/nomidotwatcher-deployment.yaml, back/node_watcher/package.json, back/server/package.json, package.json, yarn.lock
will update the image after this and it should fix the current bug (hopefully)
=> chore: bump deps, update service endpoint

back/node_watcher/kubernetes/staging/deployments/nomidotwatcher-deployment.yaml, back/node_watcher/package.json, package.json, yarn.lock
=> fix: k8s poststart hook, add back api to nodewatcher

CHANGELOG.md, back/node_watcher/CHANGELOG.md, back/node_watcher/package.json, back/server/package.json, front/context/CHANGELOG.md, front/context/package.json, front/gatsby/CHANGELOG.md, front/gatsby/package.json, front/ui-components/CHANGELOG.md, front/ui-components/package.json, package.json
yarn lerna:publish tries to publish this package too, i think it's not needed
=> chore: Make nomidot-server a private package

back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
=> feat: sync the last 50k blocks for polkassembly & nomidot (#4)

back/server/README.md
=> docs: how to connect to hosted server from local frontend in development

front/ui-components/src/InputAddress.tsx, front/ui-components/src/index.ts, front/ui-components/src/stateful/index.ts, front/ui-components/stories/InputAddress.stories.tsx
Remove it from the `stateful/` folder
=> fix(ui-components): Stateless InputAddress

back/node_watcher/src/tasks/createProposal.ts, back/node_watcher/src/tasks/createProposalStatus.ts, back/node_watcher/src/tasks/createReferendum.ts, back/node_watcher/src/tasks/createReferendumStatus.ts, back/node_watcher/src/tasks/types.ts
this time it's for referendum whose status was never updated.
Next time I'll test better!
=> fix: referendum statuses not updated

back/node_watcher/datamodel.prisma, back/node_watcher/src/generated/prisma-client/index.ts, back/node_watcher/src/generated/prisma-client/prisma-schema.ts, back/node_watcher/src/tasks/createMotion.ts, back/node_watcher/src/tasks/createPreimage.ts, back/node_watcher/src/tasks/types.ts, back/node_watcher/src/util/statuses.ts
=> feat(node watcher): Add preimage to motions

back/node_watcher/src/nodeWatcher.ts
This is purely for our convenience. Doing a lot of testing on localhost, it'd help me automate things a little.
=> feat(node-watcher): Getting the archive node from env

back/node_watcher/datamodel.prisma, back/node_watcher/src/generated/prisma-client/index.ts, back/node_watcher/src/generated/prisma-client/prisma-schema.ts, back/node_watcher/src/tasks/createMotion.ts, back/node_watcher/src/tasks/createMotionStatus.ts
=> Fix naming consistency in statuses

back/namespaces/prod-namespace.yaml, back/namespaces/staging-namespace.yaml, back/node_watcher/kubernetes/namespaces/prod-namespace.yaml, back/node_watcher/kubernetes/nomidotwatcher-job.yaml, back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml, back/server/kubernetes/server-deployment.yaml
- updated the image hashes
- stripped the namespaces down to: nodewatcher-staging and nomidot-staging
=> fix: update images

back/node_watcher/src/tasks/createTreasury.ts
=> Fix treasury query "at"

back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
As explained here https://github.com/paritytech/Nomidot/issues/221#issuecomment-594573965, I had to change the index identifier:
This job is running now.
=> last 50k with new identifier

back/server/prisma/datamodel.prisma, back/server/src/generated/prisma-client/index.ts, back/server/src/generated/prisma-client/prisma-schema.ts, back/server/src/generated/prisma.graphql, back/server/src/index.ts, back/server/src/resolvers/query.ts, back/server/src/schema.graphql
Nothing fancy. I've tested our Front with the server as a the chain-db graphql and this seems to be the only missing piece.
=> Add treasury queries to server

back/server/src/resolvers/subscription.ts, back/server/src/schema.graphql
Forgot this one when adding treasury.
=> Subscription treasury

back/server/kubernetes/server-deployment.yaml
This adds treasury subscriptions
the deployment is done already
=> Server docker image v0.3

back/node_watcher/package.json, package.json, yarn.lock
fixes https://github.com/paritytech/Nomidot/pull/242#issuecomment-601656690
The invalid character is `#`, the new private field proposal. It needs typescript >=3.8
=> Install latest @polkadot/dev

back/node_watcher/package.json, back/node_watcher/src/tasks/createReferendum.ts, back/node_watcher/src/util/filterEvents.ts, back/node_watcher/src/util/getReferendumStatus.ts, package.json, yarn.lock
closes #250
This is a copy of some helper functions from https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/democracy/util.ts
=> Support new api for referendumInfo

back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml, back/node_watcher/package.json, back/node_watcher/src/index.ts, back/node_watcher/src/nodeWatcher.ts, yarn.lock
=> Retry mechanism for nodewatcher

back/node_watcher/kubernetes/fillin-commented-job.yaml, back/node_watcher/kubernetes/nomidotwatcher-job.yaml, back/node_watcher/package.json, back/node_watcher/src/tasks/createEra.ts
https://github.com/paritytech/Nomidot/issues/260
=> fix era logging annoyance

back/node_watcher/kubernetes/fillin-commented-job.yaml, back/node_watcher/kubernetes/nomidotwatcher-job.yaml, back/node_watcher/kubernetes/v1.5/nomidotwatcher-job.yaml, back/node_watcher/kubernetes/v1.5/nomidotwatcher-last-50k-job.yaml, back/node_watcher/package.json
just updating image and setting the new env vars (currently syncing)
=> fix: v1.5 sync

front/gatsby/src/components/Layout/Header/Header.tsx
=> feat: new header

back/node_watcher/kubernetes/nodewatcher-deployment-staging.yaml, back/server/kubernetes/server-deployment.yaml
=> fix: server deployment strategy, nodewatcher replicas

back/node_watcher/kubernetes/nodewatcher-deployment-staging.yaml
=> fix: field resource

back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml, back/node_watcher/package.json
closes https://github.com/paritytech/Nomidot/issues/304
This basically redoes what was in https://github.com/paritytech/Nomidot/pull/293 but somehow didn't make it to master.
Just changing the last-50k because others aren't changed.
=> Docker image v1.2.32 again

.github/workflows/release.yml
=> github action: release.yml

front/context/src/AccountsContext.tsx, front/gatsby/src/components/BondingModal.tsx, front/gatsby/src/components/Button.tsx, front/gatsby/src/pages/index.tsx, front/gatsby/src/pages/install.tsx
redirects to an install page if extension not detected
=> feat: extension check

front/context/src/AccountsContext.tsx, front/gatsby/src/components/AccountsDropdown.tsx, front/gatsby/src/components/NominationDetails.tsx, front/gatsby/src/pages/cart.tsx
since AccountsDropdown with the onlyControllers flag will make it so user can only choose bonded account to begin with.
=> fix: remove useless check

front/context/src/util/stashes.ts, front/gatsby/src/components/BondingModal.tsx, front/gatsby/src/components/Button.tsx, front/gatsby/src/components/Tooltip.tsx, front/gatsby/src/components/index.ts, front/gatsby/src/pages/accounts.tsx
also fix the stoopid semicolon styled-compoentns error that was hiding button css 🤦‍♂️
=> fix: tooltip about stash vs contorller

back/server/src/index.ts
=> fix: Add treasury to motions

back/server/kubernetes/server-deployment.yaml, back/server/package.json, back/server/prisma/datamodel.prisma, back/server/src/generated/prisma-client/index.ts, back/server/src/generated/prisma-client/prisma-schema.ts, back/server/src/generated/prisma.graphql, back/server/src/index.ts, back/server/src/resolvers/subscription.ts, back/server/src/schema.graphql
steps that I took:
1. make sure `datamodel.prisma` in `back/server` is up to date with what is in `back/nodewatcher`
2. run `yarn prisma:deploy`
3. run `yarn gql:get-schema`
4. update `schema.graphql` to match what is in `generated/primsa-client/prisma-schema.ts` just for `type Query` and `type Subscription`
5. remove useless `subscribe` prefix on subscription names for Nomi subs. Shouldn't break anything in Polkassembly. Will make another PR to fix the frontend side.
=> chore: update server

front/gatsby/src/components/Layout/Header/Header.tsx, front/gatsby/src/components/Layout/Header/HeaderItem.tsx, front/gatsby/src/components/Layout/Header/Subheaders/BlockHeader.tsx, front/gatsby/src/components/Layout/Header/Subheaders/EraHeader.tsx, front/gatsby/src/components/Layout/Header/Subheaders/SessionHeader.tsx, front/gatsby/src/components/Layout/Header/Subheaders/StakingHeader.tsx, front/gatsby/src/components/Layout/Sidebar.tsx, front/gatsby/src/util/graphql.ts
gets the queries working again, aligned with recent server updates.
also getting rid of some console errors from the Sticky component. if we want Sticky, better do it completely with CSS
=> fix: frontend graphql

front/gatsby/src/apollo.ts
change frontend w.r.t. https://github.com/paritytech/Nomidot/pull/340
=> fix: change endpoint in dev env
