.gitignore, front/context/package.json, front/context/tsconfig.json, front/gatsby/package.json, front/ui-components/package.json, front/ui-components/tsconfig.json, lerna.json, package.json
- same author, license etc in package.jsons
- outputs js files in `lib/` instead of `build/`. In this case, users would do:
```diff
import { NavButton } from '@substrate/ui-components';
- import { NavButton } from '@substrate/ui-components/build/NavButton';
+ import { NavButton } from '@substrate/ui-components/lib/NavButton';
```
=> chore: Clean up package.jsons

front/context/src/AccountsContext.tsx, front/context/src/ApiContext.tsx, front/gatsby/src/ContextGate.tsx, front/ui-components/src/index.ts
The `api` object should be populated by the ApiContext (and not the ContextGate). This way, in light-ui, I can use the same ApiContext too.
Added a loading prop on `ApiContextProvider`: `<ApiContextProvider loading='HELLO'` />` will show HELLO while the api is loading.
=> refactor: Move ContextGate logic into ApiContext

front/ui-components/src/index.ts
Just realized that while refactoring light-ui
=> fix: Add forgotten Dropdown in ui-components

front/gatsby/gatsby-node.js, front/gatsby/src/ContextGate.tsx, front/gatsby/src/components/layout.tsx, front/gatsby/src/pages/home.tsx, front/gatsby/src/pages/index.tsx, front/gatsby/src/pages/onboarding.tsx, front/gatsby/tsconfig.json, front/ui-components/src/AccountsList.tsx, front/ui-components/src/stateful/Balance.tsx, tsconfig.json
fixes #25 
```diff
- import A from '@substrate/context/src'
+ import A from '@substrate/context'
```
Still publishes everything in the `lib/` folder
=> fix: Allow importing without src/ directory

front/context/src/KeyringContext.tsx, front/context/src/index.ts
moved from substrate/accounts-app
=> feat: add a keyring context

back/node_watcher/src/tasks/createProposal.ts
I totally missed that somehow.
It seems that I only tested with an archive node that doesn't have tabled Proposals. This causes the `depositInfo` to be undefined for any proposal that was tabled.
=> Add at(blockNumber, args) to createProposal

back/node_watcher/datamodel.prisma, back/node_watcher/src/generated/prisma-client/index.ts, back/node_watcher/src/generated/prisma-client/prisma-schema.ts, back/node_watcher/src/nodeWatcher.ts, back/node_watcher/src/tasks/createProposal.ts, back/node_watcher/src/tasks/createProposalStatus.ts, back/node_watcher/src/tasks/index.ts, back/node_watcher/src/tasks/types.ts
This adds a new proposal Status when a known proposal is updated.
This task effectively tracks `Tabled`  event, that is the only other event than `Proposed` (which is already handled in the `createProposal` task) according to https://polkadot.js.org/api/substrate/events.html#democracy
cc https://github.com/paritytech/polkassembly/issues/231
=> Add Proposal status update

back/node_watcher/src/tasks/createProposalStatus.ts
Fix of a fix :)
No status (other than Started that's created at referendum creation) was ever added.
My bad, I didn't test properly.
=> Fix: #126 fix: #125

.eslintrc.js, back/node_watcher/kubernetes/nomidotwatcher-job.yaml, back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml, back/node_watcher/src/nodeWatcher.ts, back/node_watcher/src/tasks/createBlockNumber.ts, back/node_watcher/src/tasks/createEra.ts, back/node_watcher/src/tasks/createHeartbeat.ts, back/node_watcher/src/tasks/createMotion.ts, back/node_watcher/src/tasks/createMotionStatus.ts, back/node_watcher/src/tasks/createNominationAndValidators.ts, back/node_watcher/src/tasks/createOfflineValidator.ts, back/node_watcher/src/tasks/createPreimage.ts, back/node_watcher/src/tasks/createProposal.ts, back/node_watcher/src/tasks/createProposalStatus.ts, back/node_watcher/src/tasks/createReferendum.ts, back/node_watcher/src/tasks/createReferendumStatus.ts, back/node_watcher/src/tasks/createReward.ts, back/node_watcher/src/tasks/createSession.ts, back/node_watcher/src/tasks/createSlashing.ts, back/node_watcher/src/tasks/createStake.ts, back/node_watcher/src/tasks/createTotalIssuance.ts, back/node_watcher/src/tasks/types.ts
#160 
- heartbeats: this comes from events so to query chaindb to check existence would actually be counterprodcutive.
- nominators: done
- validators: done
=> feat(#160) - minimize queries

back/server/src/resolvers/query.ts
closes https://github.com/paritytech/Nomidot/issues/192
That was a weird one. I basically change any query from 
```ts
sessions(
parent: any,
{
sessionsWhereInput,
orderBy,
skip,
after,
before,
first,
last,
}: Selectors,
{ prisma }: Context
) {
return prisma.sessions({
where: sessionsWhereInput,
orderBy,
skip,
after,
before,
first,
last,
});
},
```
to
```ts
sessions(
parent: any,
{ where, orderBy, skip, after, before, first, last }: Selectors,
{ prisma }: Context
) {
return prisma.sessions({
where,
orderBy,
skip,
after,
before,
first,
last,
});
},
```
because in this example `sessionsWhereInput` is taken as a variable and not a type (it's in { }) and therefore, there was no `where` destructured variable passed down.
=> Fix where args not taken into account

back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
Just relaunched last 50K job that stopped at block 1177733
(Origin of the stop is logged here: https://github.com/paritytech/Nomidot/issues/218)
This PR adds a dedicated index to allow us to "simply" relaunch the job, whenever it fails.
=> Add index to last 50k job

back/node_watcher/kubernetes/v1.5/nodewatcher-deployment-staging.yaml, back/node_watcher/kubernetes/v1.5/nodewatcher-service.yaml, back/node_watcher/kubernetes/v1.5/nomidotwatcher-job.yaml
closes https://github.com/paritytech/Nomidot/issues/190
just tweaked the clouddb secret to point to a the db named v1.5
I'm not sure but I wonder if it's a problem to use the same 4466 port. so far the job is running though
=> feat: v1.5 sync

.gitlab-ci.yml
Added a new stage (dockerize) to the CI, that builds new docker Images
On **master** and **tags** for
- frontend 
- server
- noder_watecher
And uploads them to the Google Container Registry in the *test-installations* project.
Builds on **master** are tagged as `:master-<short-commit-hash>` and tagged branches
are tagged as: `<tag-name>-<short-commit-hash>`.
=> Fv dockerize in ci

.gitlab-ci.yml
Better change directory before executing `docker build`, it fails for *server* & *node_watcher* atm.
=> cd before docker build

.gitlab-ci.yml
* DevOps Team decides to abandon google container registries in favour of dockerhub/[parity|paritytech]
so i changed the CI *dockerize* stage accordingly.
* Fixed the (stupid) bug in the copy command for the `yarn.lock` file that made the backend containers build fail.
=> use dockerhub as reg. & fix yarn.log copy command

front/context/src/HealthContext.tsx, front/context/src/SystemContext.tsx
Making `provider` prop optional in Health and System contexts. I need this is light-ui, it shouldn't change behavior in nomidot.
=> fix(context): Make provider optional in contexts

front/context/src/HealthContext.tsx, front/context/src/SystemContext.tsx
When we change provider, the Health & System contexts should show the values of the new provider. During the 2-3s transition period, show `undefined` instead of the old provider's value.
Tested on light-ui
=> fix(context): Reset context parameters when we change provider

CHANGELOG.md, back/node_watcher/package.json, front/context/CHANGELOG.md, front/gatsby/CHANGELOG.md, front/gatsby/package.json, lerna.json
Follows https://github.com/paritytech/Nomidot/pull/307
Unfortunately the packages have been bumped to 0.3.25 in between (but not published), so the CHANGELOG's are a bit messed up.
=> chore: Bump everywhere to 0.4.0

front/context/src/ApiPromiseContext.tsx, front/context/src/ApiRxContext.tsx, front/context/src/util/index.ts, front/context/src/util/useEffect.ts
=> fix(context): Don't instantiate API twice

back/server/kubernetes/loadbalancer.yaml
this will fix the issue of ws connection not properly terminated after a restart of *nomidot-server* pods
=> set externalTrafficPolicy to local

back/node_watcher/package.json, back/node_watcher/src/tasks/createBlockNumber.ts, back/node_watcher/src/tasks/createSession.ts, back/node_watcher/src/tasks/types.ts
instead of relying on prisma to error and not write, just check existence before write...
it should get rid of those `Error: Unique Constaint Invariant Violation`s
=> fix: dont try to write on unique constraint invariant

back/server/kubernetes/nodewatcher-server-ingress.yaml, back/server/kubernetes/nodewatcher-server-service.yaml
This change adds a new service + ingress controller to make the nodewatcher/nomidot server available from outside the *dashboards-cluster-1* via the url: `https://test.nodewatcher-server.polkassembly.io`.
This new service offers the same functionality as the existing `Nomidot/back/server/kubernetes/loadbalancer.yaml`, but looks like being more reliably handling web-socket connections.
=> added ingress controler for nodewatcher server

back/node_watcher/package.json, front/context/package.json, package.json, yarn.lock
Btw we're now using `@substrate/context` in prod in Polkassembly :)
- ran `yarn start` on Gatsby
- ran the node watcher
Can you please release a new @substrate/context version then?
=> chore: bump @polkadot/api to 1.13.1

front/context/src/AccountsContext.tsx, front/gatsby/src/components/AccountsDropdown.tsx, front/gatsby/src/components/Cart/CartItems.tsx, front/gatsby/src/components/Layout/Header/Header.tsx, front/gatsby/src/components/Layout/Layout.tsx, front/gatsby/src/components/NominationDetails.tsx, front/gatsby/src/components/Tooltip.tsx, front/gatsby/src/pages/cart.tsx, front/gatsby/src/util/validateExtrinsic.ts
`api.tx.staking.nominate` is signed by the controller, and whatever is the `activeBond` in the signing account is used as the nomination amount.
So this PR is removing the input amount, using the active bond of the selected account to estimate rewards and also adding tooltips to explain this, as well as the unbonding period.
also doing some refactoring
all this information from the docs for `api.tx.staking.nominate` needs to be communicated somehow:
* Declare the desire to nominate `targets` for the origin controller.
* Effects will be felt at the beginning of the next era. This can only be called when
* [`EraElectionStatus`] is `Closed`.
* The dispatch origin for this call must be _Signed_ by the controller, not the stash.
* And, it can be only called when [`EraElectionStatus`] is …
=> fix: cart page nomination UX

front/context/src/HealthContext.tsx
Subtle bug: when in light-ui I'm changing providers: if the old provider was syncing or not syncing, it should not have any effect on the syncing status of the new provider
=> fix(context): Reset syncing to true when chaning provider

back/node_watcher/package.json
got error while publishing
```
lerna info publish Publishing packages to npm...
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 1893ms
lerna http fetch GET 200 https://registry.npmjs.org/-/org/amaurymartiny/package?format=cli 1045ms
lerna info Checking two-factor auth mode
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 563ms
lerna http fetch PUT 400 https://registry.npmjs.org/@substrate%2fnode-watcher 7092ms
lerna ERR! E400 This package contains unacceptable content. Contact support@npmjs.com.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
so I just thought of not publishing anymore. We can re-publish it later, when it's more stable? …
=> chore(node-watcher): Don't publish package
